In [3]:
#linear regresion eg of regression
from sklearn.linear_model import LinearRegression
import numpy as np
#sample data
X=np.array([[1],[2],[3],[4]])
y=np.array([2,4,6,8])
#model training
model=LinearRegression()
model.fit(X,y)
#prediction
prediction=model.predict([[40]])
print(f"predicted value:{prediction}")

predicted value:[80.]

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score

In [3]:
df=pd.read_csv("USA_Housing.CSV")
df

,Avg. Area Income,Avg. Area House Age,Avg. Area Number of Rooms,Avg. Area Number of Bedrooms,Area Population,Price,Address
0,79545.458574,5.682861,7.009188,4.09,23086.800503,1.059034e+06,"208 Michael Ferry Apt. 674\nLaurabury, NE 3701..."
1,79248.642455,6.002900,6.730821,3.09,40173.072174,1.505891e+06,"188 Johnson Views Suite 079\nLake Kathleen, CA..."
2,61287.067179,5.865890,8.512727,5.13,36882.159400,1.058988e+06,"9127 Elizabeth Stravenue\nDanieltown, WI 06482..."
3,63345.240046,7.188236,5.586729,3.26,34310.242831,1.260617e+06,USS Barnett\nFPO AP 44820
4,59982.197226,5.040555,7.839388,4.23,26354.109472,6.309435e+05,USNS Raymond\nFPO AE 09386
...,...,...,...,...,...,...,...
4995,60567.944140,7.830362,6.137356,3.46,22837.361035,1.060194e+06,USNS Williams\nFPO AP 30153-7653
4996,78491.275435,6.999135,6.576763,4.02,25616.115489,1.482618e+06,"PSC 9258, Box 8489\nAPO AA 42991-3352"
4997,63390.686886,7.250591,4.805081,2.13,33266.145490,1.030730e+06,"4215 Tracy Garden Suite 076\nJoshualand, VA 01..."
4998,68001.331235,5.534388,7.130144,5.44,42625.620156,1.198657e+06,USS Wallace\nFPO AE 73316
4999,65510.581804,5.992305,6.792336,4.07,46501.283803,1.298950e+06,"37778 George Ridges Apt. 509\nEast Holly, NV 2..."

In [6]:
#exaple dataset ,house_size,room-->price
df=pd.read_csv("USA_Housing.CSV")
x=df[["Avg. Area Income","Avg. Area Number of Bedrooms"]]#features
y=df[["Price"]]
x,y

(      Avg. Area Income  Avg. Area Number of Bedrooms
 0         79545.458574                          4.09
 1         79248.642455                          3.09
 2         61287.067179                          5.13
 3         63345.240046                          3.26
 4         59982.197226                          4.23
 ...                ...                           ...
 4995      60567.944140                          3.46
 4996      78491.275435                          4.02
 4997      63390.686886                          2.13
 4998      68001.331235                          5.44
 4999      65510.581804                          4.07

 [5000 rows x 2 columns],
              Price
 0     1.059034e+06
 1     1.505891e+06
 2     1.058988e+06
 3     1.260617e+06
 4     6.309435e+05
 ...            ...
 4995  1.060194e+06
 4996  1.482618e+06
 4997  1.030730e+06
 4998  1.198657e+06
 4999  1.298950e+06

 [5000 rows x 1 columns])

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [12]:
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [14]:
y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("mse=",mse)
print("r2_score",r2)

mse= 71626684242.45575
r2_score 0.41782284193897345

In [15]:
new_house=np.array([[1200,3]])
pred_price=model.predict(new_house)
print("predicted_house:",pred_price[0])

predicted_house: [-236949.82894202]

D:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [5]:
df=pd.read_csv("Student.csv")
x=df[["Maths","Physics"]]
y=df["Result"]

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [7]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [9]:
y_pred=model.predict(x_test)

In [11]:
acc=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
print("Accuracy:",acc)
print("confuison matrix:\n",cm)
print("classification report:\n",classification_report(y_test,y_pred))

Accuracy: 0.76
confuison matrix:
 [[130  15]
 [ 33  22]]
classification report:
               precision    recall  f1-score   support

           0       0.80      0.90      0.84       145
           1       0.59      0.40      0.48        55

    accuracy                           0.76       200
   macro avg       0.70      0.65      0.66       200
weighted avg       0.74      0.76      0.74       200

In [12]:
new_student=np.array([[67,89]])
pred_class=model.predict(new_student)
pred_prob=model.predict_proba(new_student)[0,1]
print("predicted class(1=pass,0=fail):",pred_class)
print("probability of passing:",pred_prob)

predicted class(1=pass,0=fail): [1]
probability of passing: 0.663021011182717

D:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
D:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [22]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

#data=pd.read_csv("Customer_data.csv")
#x=data[["age","income"]]
#y=data["satisfaction_score"]

data=pd.read_csv("Social_Network_Ads.csv")

data

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [23]:

x=data[["Age","EstimatedSalary"]]
y=data["Purchased"]

In [24]:
#create knn model
model=KNeighborsClassifier(n_neighbors=5)

In [25]:
#train model
model.fit(x,y)

#predict for new user
new_customer=[[30,0]] #age=30 salary=42000
prediction=model.predict(new_customer)
print("LOAN TAKEN:",prediction[0])

LOAN TAKEN: 0

D:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [26]:
#ALSO CALLED AS LASY LEARNING ALGORITHM.it will take input and classify based on the 5 neighbprs it will predict .hyperparameter means can change the parameters
#can do regression and classification

In [27]:
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor

#data=pd.read_csv("Customer_data.csv")
#x=data[["age","income"]]
#y=data["satisfaction_score"]

data=pd.read_csv("Social_Network_Ads.csv")
x=data[["Age","EstimatedSalary"]]
y=data["Purchased"]

In [28]:
model=KNeighborsRegressor(n_neighbors=5)

In [29]:
#train model
model.fit(x,y)

#predict for new user
new_customer=[[30,0]] #age=30 salary=42000
prediction=model.predict(new_customer)
print("LOAN TAKEN:",prediction[0])

LOAN TAKEN: 0.0

D:\Users\HP\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(

In [26]:
#decision tree
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [27]:
df=pd.read_csv("loan_data.csv")

In [28]:
df["Loan_Status"]=df["Loan_Status"].map({"y":1,"N":0})
df["Property_Area"]=df["Property_Area"].map({"Urban":2,"Semiurban":1,"Rural":0})

In [32]:
df.isnull().sum()

Loan_ID                0
Gender                13
Married                3
Dependents            15
Education              0
Self_Employed         32
ApplicantIncome        0
CoapplicantIncome      0
LoanAmount            22
Loan_Amount_Term      14
Credit_History        50
Property_Area          0
Loan_Status          422
dtype: int64

In [39]:
#1. Fill categorical columns with mode
df["Gender"].fillna(df["Gender"].mode()[0], inplace=True)

df["Married"].fillna(df["Married"].mode()[0], inplace=True)

df["Dependents"].fillna(df["Dependents"].mode()[0], inplace=True)

df["Self_Employed"].fillna(df["Self_Employed"].mode()[0], inplace=True)

df["Credit_History"].fillna(df["Credit_History"].mode()[0], inplace=True)

df["Loan_Status"].fillna(df["Loan_Status"].mode()[0], inplace=True)
#2. Fill numerical columns with mean

df["LoanAmount"].fillna(df["LoanAmount"].mean(), inplace=True)

df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].mean(), inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_6860\1567909122.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Credit_History"].fillna(df["Credit_History"].mode()[0], inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_6860\1567909122.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["LoanAmount"].fillna(df["LoanAmount"].mean(), inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_6860\1567909122.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Loan_Amount_Term"].fillna(df["Loan_Amount_Term"].mean(), inplace=True)

In [40]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [41]:
x=df[["ApplicantIncome","LoanAmount","Credit_History","Property_Area"]]
y=df["Loan_Status"]

In [42]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [43]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [48]:
y_pred=model.predict(x_test)

In [49]:
print("accuracy:",accuracy_score(y_test,y_pred))

accuracy: 1.0